# Generated by Django 4.2.20 on 2025-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='icon',
            field=models.ImageField(upload_to='Counter/'),
        ),
    ]
