# Generated by Django 4.2.20 on 2025-04-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_counter_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
