# Generated by Django 4.2.20 on 2025-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_counter_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('section2', 'بخش دوم'), ('section4', 'بخش چهارم')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='تیتر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='home_sections/', verbose_name='تصویر')),
                ('button_text', models.CharField(default='اطلاعات بیشتر', max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
