# Generated by Django 4.2.20 on 2025-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('section2', 'بخش دوم'), ('section4', 'بخش چهارم'), ('section6', 'بخش ششم')], max_length=20),
        ),
    ]
