# Generated by Django 4.2.20 on 2025-04-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_homesection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('logo', models.ImageField(upload_to='site_logo/', verbose_name='لوگو')),
                ('logo_width', models.PositiveIntegerField(default=150, verbose_name='عرض لوگو (پیکسل)')),
                ('logo_height', models.PositiveIntegerField(default=60, verbose_name='ارتفاع لوگو (پیکسل)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
